[package]
name = "name"
version = "0.1.0"
authors = ["Tibor Prokai <tibor@kotem.com>"]
edition = "2018"
repository = "https://github.com/tib888/name"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
